### ISSUE TITLE
Invalid value for argument `gender`: "OUTRO"

### ISSUE THREAD

**Issue by davidgaspardev** [davidgaspardev/web-acton#1]
Issue with user creation on the frontend.

```bash
Invalid "prisma.users.create()" invocation:

{
  data: {
    fullname: "Valdirene Pasto",
    email: "val@val.com",
    whatsapp: "48984596889",
    gender: "OUTRO"
            ~~~~~~~
  }
}

Invalid value for argument `gender`. Expected Gender.
    at Ur (C:\Users\da057257\Desktop\Projects\me\acton\node_modules\@prisma\client\runtime\library.js:115:5803)   
    at zr.handleRequestError (C:\Users\da057257\Desktop\Projects\me\acton\node_modules\@prisma\client\runtime\library.js:122:8007)
    at zr.handleAndLogRequestError (C:\Users\da057257\Desktop\Projects\me\acton\node_modules\@prisma\client\runtime\library.js:122:7697)
    at zr.request (C:\Users\da057257\Desktop\Projects\me\acton\node_modules\@prisma\client\runtime\library.js:122:7307)
    at async POST (webpack-internal:///(sc_server)/./app/api/users/route.ts:14:25)
    at async eval (webpack-internal:///(sc_server)/./node_modules/next/dist/server/future/route-modules/app-route/module.js:242:37) {
  clientVersion: '5.0.0'
}
```

**Comment by davidgaspardev** [comment]
In Prisma, 'OUTRO' is mapped to 'OUTROS' in plural.

```prisma
enum Gender {
  MASCULINO
  FEMININO
  TRANS
  OUTROS // It isn't "OUTRO"
  DESCONHECIDO
}
```
